### ISSUE TITLE
Missing region in aws provider causes script to fail

### ISSUE THREAD

**Issue by aaronclong** [QuiNovas/terraform-aws-vpc-peering#6]
![image](https://user-images.githubusercontent.com/7354981/76644467-645d6f00-652d-11ea-8cae-31ede0b95cdd.png)

**Comment by vchinnakotla** [comment]
@aaronclong Sorry, that the readme doesn't have an example. I'll update it.
This module expects that user will pass providers block with accepter and requester information declared in the root module.

For .eg
`
provider "aws" {
  alias                           = "ohio"
  allowed_account_ids = local.allowed_account_ids
  region                        = "us-east-2"
}

provider "aws" {
  alias                            = "n_virginia"
  allowed_account_ids  = local.allowed_account_ids
  region                         = "us-east-1"
}

module "peering" {
  accepter_vpc_id = "vpc-123456789abc"

  providers = {
    aws.accepter   = aws.ohio
    aws.requester  = aws.n_virginia
  }

  requester_vpc_id = "vpc-abcdefgh123"
  source                  = "QuiNovas/vpc-peering/aws"
  version                 = "3.0.1"
}`
